version: '3.5'
services:
  db:
    image: postgres:14-alpine
    shm_size: '2gb'
    command: postgres -c work_mem=30MB
    environment:
      - POSTGRES_USER=animus
      - POSTGRES_PASSWORD=animus
      - POSTGRES_DB=animus
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql-static/data
    ports:
      - "${DB_PORT:-5432}:5432"

  wait-for-db:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: db:5432

  db-migrate:
    image: gomicro/goose
    command: goose -dir "/migrations" postgres "host=animus user=animus dbname=animus password=animus sslmode=disable" up
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./db/migrations:/migrations

  ipfs:
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - ./devenv/data/ipfs:/ipfsdata
    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:5001:5001"

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150"
      - "4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171"
