version: '3.5'
services:
  db:
    image: postgres:14-alpine
    shm_size: '2gb'
    command: postgres -c work_mem=30MB
    environment:
      POSTGRES_USER: "${DB_USERNAME:-animus}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-animus}"
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql-static/data
    ports:
      - "${DB_PORT:-5432}:5432"

  ipfs:
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      # ipfs node is private
      # ./data/ipfs/config::Bootstrap list is empty (no bootstrap)
      # swarm key is provided in the devenv
      - ./devenv/ipfs:/ipfsdata
    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:5001:5001"
